import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import Topbar from '../../components/shell/Topbar'
import { Badge } from '../../components/ui'
import Icon from '../../icons'
import { getProject } from '../../services/projects'
import { getAdminLearningPath, publishLearningPath } from '../../services/learningPath'

export default function AdminPathPreview() {
  const { projectId } = useParams()
  const navigate = useNavigate()
  const [project, setProject] = useState(null)
  const [path, setPath] = useState(null)
  const [loading, setLoading] = useState(true)
  const [publishing, setPublishing] = useState(false)
  const [published, setPublished] = useState(false)

  useEffect(() => {
    if (!projectId) return
    getProject(projectId).then(setProject).catch(() => {})
    getAdminLearningPath(projectId)
      .then(p => { setPath(p); setPublished(p.is_published) })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [projectId])

  const handlePublish = async () => {
    if (!path) return
    setPublishing(true)
    try {
      await publishLearningPath(projectId, path.id)
      setPublished(true)
    } finally {
      setPublishing(false)
    }
  }

  if (loading) {
    return (
      <>
        <Topbar crumbs={['Projects', '…', 'Path preview']} search={false} />
        <div className="viewport"><div className="page-body"><div className="skeleton" style={{ height: 200 }} /></div></div>
      </>
    )
  }

  const modules = path?.modules ?? []
  const allSameWeek = modules.length > 0 && modules.every(m => m.week_number === modules[0].week_number)
  const totalWeeks = modules.length > 0 ? Math.max(...modules.map((m, i) => allSameWeek ? i + 1 : (m.week_number ?? i + 1))) : 0

  return (
    <>
      <Topbar crumbs={['Projects', project?.name ?? '…', 'Path preview']} search={false} actions={
        <>
          <button className="btn" onClick={() => navigate(`/v2/admin/projects/${projectId}/paths`)}>
            <Icon name="chat" size={14} /> Edit via chat
          </button>
          {!published ? (
            <button className="btn primary" onClick={handlePublish} disabled={publishing || modules.length === 0}>
              <Icon name="check" size={14} /> {publishing ? 'Publishing…' : 'Accept & publish'}
            </button>
          ) : (
            <button className="btn" onClick={() => navigate(`/v2/admin/projects/${projectId}`)}>
              <Icon name="check" size={14} /> Published — go to project
            </button>
          )}
        </>
      } />
      <div className="viewport">
        <div className="page-header">
          <div>
            <div className="row" style={{ gap: 8 }}>
              <h1>{project?.name ?? '…'} · {totalWeeks}-week onboarding</h1>
              <Badge tone={published ? 'success' : 'warning'} dot>{published ? 'Published' : 'Draft'}</Badge>
              <Badge tone="ai" dot>AI generated</Badge>
            </div>
            <div className="sub">{modules.length} modules · Generated by Atlas</div>
          </div>
        </div>

        <div className="page-body">
          <div className="col" style={{ gap: 16 }}>
            {modules.length === 0 ? (
              <div className="empty card">
                <div className="illu"><Icon name="layers" /></div>
                <h3>No path generated yet</h3>
                <p>Go back and use the chat to generate a learning path first.</p>
                <button className="btn primary" onClick={() => navigate(`/v2/admin/projects/${projectId}/paths`)}>
                  Open path designer
                </button>
              </div>
            ) : modules.map((m, i) => {
              const week = allSameWeek ? i + 1 : (m.week_number ?? i + 1)
              const concepts = m.key_concepts
                ? m.key_concepts.split(',').map(s => s.trim()).filter(Boolean)
                : []
              const sectionCount = m.chunks?.length ?? 0

              return (
                <div key={m.id ?? i} className="card">
                  <div className="card-body">
                    <div className="row" style={{ alignItems: 'flex-start', gap: 16 }}>
                      {/* Week badge column */}
                      <div style={{ flexShrink: 0, textAlign: 'center' }}>
                        <div style={{
                          width: 56, height: 56, borderRadius: 12,
                          background: 'var(--accent-soft)', color: 'var(--accent)',
                          display: 'grid', placeItems: 'center',
                        }}>
                          <div>
                            <div style={{ fontSize: 10, opacity: 0.7, fontWeight: 600, letterSpacing: '0.06em' }}>WK</div>
                            <div style={{ fontSize: 22, lineHeight: 1, fontWeight: 700 }}>{week}</div>
                          </div>
                        </div>
                      </div>

                      {/* Content column */}
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div className="row" style={{ justifyContent: 'space-between', alignItems: 'center', gap: 8 }}>
                          <h3 style={{ margin: 0, fontSize: 16, letterSpacing: '-0.01em' }}>{m.title}</h3>
                          <div className="row" style={{ gap: 6, flexShrink: 0 }}>
                            {sectionCount > 0 && (
                              <Badge tone="outline">
                                <Icon name="docs" size={11} /> {sectionCount} sections
                              </Badge>
                            )}
                          </div>
                        </div>

                        {m.summary && (
                          <div className="muted" style={{ marginTop: 6, fontSize: 13, lineHeight: 1.5 }}>
                            {m.summary}
                          </div>
                        )}

                        {concepts.length > 0 && (
                          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 12 }}>
                            {concepts.map(c => (
                              <span key={c} style={{
                                padding: '3px 10px', borderRadius: 99, fontSize: 12,
                                background: 'var(--surface-2)', color: 'var(--text-2)',
                                border: '1px solid var(--border)',
                              }}>
                                {c}
                              </span>
                            ))}
                          </div>
                        )}

                        {m.chunks && m.chunks.length > 0 && (
                          <div style={{ marginTop: 14, display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 8 }}>
                            {m.chunks.slice(0, 6).map((c, ci) => (
                              <div key={c.id ?? ci} style={{
                                padding: '8px 12px', background: 'var(--surface-2)',
                                borderRadius: 8, fontSize: 12, display: 'flex', alignItems: 'flex-start', gap: 8,
                                border: '1px solid var(--border)',
                              }}>
                                <span style={{
                                  width: 18, height: 18, borderRadius: 99, background: 'var(--surface)',
                                  border: '1px solid var(--border)', display: 'grid', placeItems: 'center',
                                  fontSize: 10, color: 'var(--text-3)', fontFamily: 'var(--font-mono)', flexShrink: 0,
                                }}>
                                  {ci + 1}
                                </span>
                                <span style={{ color: 'var(--text-2)', lineHeight: 1.4 }}>
                                  {(c.content ?? '').slice(0, 60)}{(c.content ?? '').length > 60 ? '…' : ''}
                                </span>
                              </div>
                            ))}
                            {m.chunks.length > 6 && (
                              <div style={{ padding: '8px 12px', background: 'var(--surface-2)', borderRadius: 8, fontSize: 12, color: 'var(--text-3)', display: 'flex', alignItems: 'center', border: '1px solid var(--border)' }}>
                                +{m.chunks.length - 6} more sections
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              )
            })}

            {modules.length > 0 && (
              <div className="ai-surface" style={{ padding: 18, display: 'flex', alignItems: 'center', gap: 14 }}>
                <div style={{ width: 44, height: 44, borderRadius: 10, background: 'white', color: 'var(--ai)', display: 'grid', placeItems: 'center' }}>
                  <Icon name="target" size={22} />
                </div>
                <div style={{ flex: 1 }}>
                  <strong>Final readiness evaluation</strong>
                  <div className="muted" style={{ fontSize: 12.5, marginTop: 2 }}>
                    Mixed-format questions across all weeks. Pass at 75% to be marked production-ready.
                  </div>
                </div>
                <Badge tone="ai">Required</Badge>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  )
}
